### imports

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.config.experimental.list_physical_devices('GPU')

[]

### 지난강의 보충

`-` max, min, sum, mean

In [3]:
a= tf.constant([1.0,2.0,3.0,4.0])
a

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [4]:
print(min(a), max(a))

tf.Tensor(1.0, shape=(), dtype=float32) tf.Tensor(4.0, shape=(), dtype=float32)


In [5]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

#### concat, stack

`-` 예제: (2,3,4,5) stack (2,3,4,5) -> (?,?,?,?,?)

In [6]:
a = tf.reshape(tf.constant(range(2*3*4*5)),(2,3,4,5))
b = -a

In [7]:
a

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]], dtype=int32)>

**case1** (1,2,3,4,5) stack (1,2,3,4,5) --> (2,2,3,4,5) # axis=0


In [8]:
#shape=(2, 2, 3, 4, 5)은 5차원 배열이며, 배열의 구조를 다음과 같이 설명:
# 2개의 큰 묶음이 있고, 각 큰 묶음 안에 2개의 작은 묶음이 있으며,
# 각 작은 묶음 안에 3개의 작은 덩어리가 있으며, 각 작은 덩어리 안에 4개의 작은 묶음이 있으며,
# 각 작은 묶음 안에 5개의 요소가 있다는 것을 의미

In [9]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[  60,   61,   62,   63,   64],
          [  65,   66,   67,   68,   69],
          [  70,   71,   72,   73,   74],
          [  75,   76,   77,   78,   79]],

         [[  80,   81,   82,   83,   84],
          [  85,   86,   87,   88,   89],
          [  90,   91,   92,   93,   94],
          [  95,   96,   97,   98,   99]],

         [[ 100,  101,  102,  103,  104],
          [ 105,  106,  107,  108,  109],
         

**case2** (2,1,3,4,5) stack (2,1,3,4,5) --> (2,2,3,4,5) # axis=1

In [10]:
tf.stack([a,b],axis=1)

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[   0,   -1,   -2,   -3,   -4],
          [  -5,   -6,   -7,   -8,   -9],
          [ -10,  -11,  -12,  -13,  -14],
          [ -15,  -16,  -17,  -18,  -19]],

         [[ -20,  -21,  -22,  -23,  -24],
          [ -25,  -26,  -27,  -28,  -29],
          [ -30,  -31,  -32,  -33,  -34],
          [ -35,  -36,  -37,  -38,  -39]],

         [[ -40,  -41,  -42,  -43,  -44],
          [ -45,  -46,  -47,  -48,  -49],
         

**case3** (2,3,1,4,5) stack (2,3,1,4,5) --> (2,3,2,4,5) # axis=2

In [11]:
#shape=(2, 3, 2, 4, 5)은 5차원 배열이며, 배열의 구조를 다음과 같이 설명:
# 2개의 큰 묶음이 있고, 각 큰 묶음 안에 3개의 작은 묶음이 있으며,
# 각 작은 묶음 안에 2개의 작은 덩어리가 있으며, 각 작은 덩어리 안에 4개의 작은 묶음이 있으며,
# 각 작은 묶음 안에 5개의 요소가 있다는 것을 의미

In [12]:
tf.stack([a,b],axis=2)

<tf.Tensor: shape=(2, 3, 2, 4, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[   0,   -1,   -2,   -3,   -4],
          [  -5,   -6,   -7,   -8,   -9],
          [ -10,  -11,  -12,  -13,  -14],
          [ -15,  -16,  -17,  -18,  -19]]],


        [[[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[ -20,  -21,  -22,  -23,  -24],
          [ -25,  -26,  -27,  -28,  -29],
          [ -30,  -31,  -32,  -33,  -34],
          [ -35,  -36,  -37,  -38,  -39]]],


        [[[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]],

         [[ -40,  -41,  -42,  -43,  -44],
          [ -45,  -46,  -47,  -48,  -49],
       

**case4** (2,3,4,1,5) stack (2,3,4,1,5)  -->  (2,3,4,2,5) # axis=3

In [13]:
tf.stack([a,b],axis=-2)

<tf.Tensor: shape=(2, 3, 4, 2, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   0,   -1,   -2,   -3,   -4]],

         [[   5,    6,    7,    8,    9],
          [  -5,   -6,   -7,   -8,   -9]],

         [[  10,   11,   12,   13,   14],
          [ -10,  -11,  -12,  -13,  -14]],

         [[  15,   16,   17,   18,   19],
          [ -15,  -16,  -17,  -18,  -19]]],


        [[[  20,   21,   22,   23,   24],
          [ -20,  -21,  -22,  -23,  -24]],

         [[  25,   26,   27,   28,   29],
          [ -25,  -26,  -27,  -28,  -29]],

         [[  30,   31,   32,   33,   34],
          [ -30,  -31,  -32,  -33,  -34]],

         [[  35,   36,   37,   38,   39],
          [ -35,  -36,  -37,  -38,  -39]]],


        [[[  40,   41,   42,   43,   44],
          [ -40,  -41,  -42,  -43,  -44]],

         [[  45,   46,   47,   48,   49],
          [ -45,  -46,  -47,  -48,  -49]],

         [[  50,   51,   52,   53,   54],
          [ -50,  -51,  -52,  -53,  -54

**case5** (2,3,4,5,1) stack (2,3,4,5,1) --> (2,3,4,5,2) # axis=4

In [14]:
tf.stack([a,b],axis=-1)

<tf.Tensor: shape=(2, 3, 4, 5, 2), dtype=int32, numpy=
array([[[[[   0,    0],
          [   1,   -1],
          [   2,   -2],
          [   3,   -3],
          [   4,   -4]],

         [[   5,   -5],
          [   6,   -6],
          [   7,   -7],
          [   8,   -8],
          [   9,   -9]],

         [[  10,  -10],
          [  11,  -11],
          [  12,  -12],
          [  13,  -13],
          [  14,  -14]],

         [[  15,  -15],
          [  16,  -16],
          [  17,  -17],
          [  18,  -18],
          [  19,  -19]]],


        [[[  20,  -20],
          [  21,  -21],
          [  22,  -22],
          [  23,  -23],
          [  24,  -24]],

         [[  25,  -25],
          [  26,  -26],
          [  27,  -27],
          [  28,  -28],
          [  29,  -29]],

         [[  30,  -30],
          [  31,  -31],
          [  32,  -32],
          [  33,  -33],
          [  34,  -34]],

         [[  35,  -35],
          [  36,  -36],
          [  37,  -37],
          [  38, 

`-` 예제: (2,3,4), (2,3,4), (2,3,4)

In [15]:
a= tf.reshape(tf.constant(range(2*3*4)),(2,3,4))
b= -a
c= 2*a

(예시1) (2,3,4), (2,3,4), (2,3,4) $\to$ (6,3,4)

In [16]:
tf.concat([a,b,c],axis=0)

<tf.Tensor: shape=(6, 3, 4), dtype=int32, numpy=
array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]],

       [[  0,   2,   4,   6],
        [  8,  10,  12,  14],
        [ 16,  18,  20,  22]],

       [[ 24,  26,  28,  30],
        [ 32,  34,  36,  38],
        [ 40,  42,  44,  46]]], dtype=int32)>

(예시2) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,9,4)

In [17]:
tf.concat([a,b,c],axis=1)

<tf.Tensor: shape=(2, 9, 4), dtype=int32, numpy=
array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11],
        [  0,   2,   4,   6],
        [  8,  10,  12,  14],
        [ 16,  18,  20,  22]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23],
        [ 24,  26,  28,  30],
        [ 32,  34,  36,  38],
        [ 40,  42,  44,  46]]], dtype=int32)>

(예시3) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,12)

In [18]:
tf.concat([a,b,c],axis=-1)

<tf.Tensor: shape=(2, 3, 12), dtype=int32, numpy=
array([[[  0,   1,   2,   3,   0,  -1,  -2,  -3,   0,   2,   4,   6],
        [  4,   5,   6,   7,  -4,  -5,  -6,  -7,   8,  10,  12,  14],
        [  8,   9,  10,  11,  -8,  -9, -10, -11,  16,  18,  20,  22]],

       [[ 12,  13,  14,  15, -12, -13, -14, -15,  24,  26,  28,  30],
        [ 16,  17,  18,  19, -16, -17, -18, -19,  32,  34,  36,  38],
        [ 20,  21,  22,  23, -20, -21, -22, -23,  40,  42,  44,  46]]],
      dtype=int32)>

(예시4) (2,3,4), (2,3,4), (2,3,4) $\to$ (3,2,3,4)


In [19]:
tf.stack([a,b,c],axis=0)   #3차원이 4차원이 됐으므로 stack 필요 #첫번째 자리에 축 끼워넣음

<tf.Tensor: shape=(3, 2, 3, 4), dtype=int32, numpy=
array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],

        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]],


       [[[  0,  -1,  -2,  -3],
         [ -4,  -5,  -6,  -7],
         [ -8,  -9, -10, -11]],

        [[-12, -13, -14, -15],
         [-16, -17, -18, -19],
         [-20, -21, -22, -23]]],


       [[[  0,   2,   4,   6],
         [  8,  10,  12,  14],
         [ 16,  18,  20,  22]],

        [[ 24,  26,  28,  30],
         [ 32,  34,  36,  38],
         [ 40,  42,  44,  46]]]], dtype=int32)>

(예시5) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,3,4)

In [20]:
tf.stack([a,b,c],axis=1)

<tf.Tensor: shape=(2, 3, 3, 4), dtype=int32, numpy=
array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],

        [[  0,  -1,  -2,  -3],
         [ -4,  -5,  -6,  -7],
         [ -8,  -9, -10, -11]],

        [[  0,   2,   4,   6],
         [  8,  10,  12,  14],
         [ 16,  18,  20,  22]]],


       [[[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]],

        [[-12, -13, -14, -15],
         [-16, -17, -18, -19],
         [-20, -21, -22, -23]],

        [[ 24,  26,  28,  30],
         [ 32,  34,  36,  38],
         [ 40,  42,  44,  46]]]], dtype=int32)>

(예시6) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,3,4)

In [21]:
tf.stack([a,b,c],axis=2)

<tf.Tensor: shape=(2, 3, 3, 4), dtype=int32, numpy=
array([[[[  0,   1,   2,   3],
         [  0,  -1,  -2,  -3],
         [  0,   2,   4,   6]],

        [[  4,   5,   6,   7],
         [ -4,  -5,  -6,  -7],
         [  8,  10,  12,  14]],

        [[  8,   9,  10,  11],
         [ -8,  -9, -10, -11],
         [ 16,  18,  20,  22]]],


       [[[ 12,  13,  14,  15],
         [-12, -13, -14, -15],
         [ 24,  26,  28,  30]],

        [[ 16,  17,  18,  19],
         [-16, -17, -18, -19],
         [ 32,  34,  36,  38]],

        [[ 20,  21,  22,  23],
         [-20, -21, -22, -23],
         [ 40,  42,  44,  46]]]], dtype=int32)>

(예시7) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,4,3)

In [22]:
tf.stack([a,b,c],axis=-1)

<tf.Tensor: shape=(2, 3, 4, 3), dtype=int32, numpy=
array([[[[  0,   0,   0],
         [  1,  -1,   2],
         [  2,  -2,   4],
         [  3,  -3,   6]],

        [[  4,  -4,   8],
         [  5,  -5,  10],
         [  6,  -6,  12],
         [  7,  -7,  14]],

        [[  8,  -8,  16],
         [  9,  -9,  18],
         [ 10, -10,  20],
         [ 11, -11,  22]]],


       [[[ 12, -12,  24],
         [ 13, -13,  26],
         [ 14, -14,  28],
         [ 15, -15,  30]],

        [[ 16, -16,  32],
         [ 17, -17,  34],
         [ 18, -18,  36],
         [ 19, -19,  38]],

        [[ 20, -20,  40],
         [ 21, -21,  42],
         [ 22, -22,  44],
         [ 23, -23,  46]]]], dtype=int32)>

`-` 예제: (2,3,4) (4,3,4) $\to$ (6,3,4)

In [23]:
a=tf.reshape(tf.constant(range(2*3*4)),(2,3,4))   #3차원이 3차원 됐으니까 concat 사용
b=tf.reshape(-tf.constant(range(4*3*4)),(4,3,4))

In [24]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(6, 3, 4), dtype=int32, numpy=
array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]],

       [[-24, -25, -26, -27],
        [-28, -29, -30, -31],
        [-32, -33, -34, -35]],

       [[-36, -37, -38, -39],
        [-40, -41, -42, -43],
        [-44, -45, -46, -47]]], dtype=int32)>

In [25]:
tf.concat([a,b],axis=1)    #디멘션이 다르므로 연산 불가능

InvalidArgumentError: ignored

In [26]:
tf.concat([a,b],axis=2)

InvalidArgumentError: ignored

`-` (2,2) @ (2,) 의 연산?

**numpy**

In [27]:
np.array([[1,0],[0,1]])

array([[1, 0],
       [0, 1]])

In [ ]:
np.array([[1,0],[0,1]]) @ np.array([77,-88])   #뒤에 1이 생략된 게 아니라 계산될 때 알아서 벡터가 조절

In [31]:
np.array([77,-88]) @ np.array([[1,0],[0,1]])

array([ 77, -88])

In [29]:
np.array([[1,0],[0,1]]) @ np.array([77,-88]).reshape(2,1)

array([[ 77],
       [-88]])

In [32]:
np.array([77,-88]).reshape(2,1) @ np.array([[1,0],[0,1]])     #벡터를 2, 1로 선언했기 때문에 디멘션이 맞지 않음

ValueError: ignored

In [30]:
np.array([77,-88]).reshape(1,2) @ np.array([[1,0],[0,1]])

array([[ 77, -88]])

**tensorflow**

In [33]:
I = tf.constant([[1.0,0.0],[0.0,1.0]])
x = tf.constant([77.0,-88.0])

In [34]:
I @ x   #디멘션 맞지 않아서 계산 안됨

InvalidArgumentError: ignored

In [35]:
x @ I

InvalidArgumentError: ignored

In [36]:
I @ tf.reshape(x,(2,1))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 77.],
       [-88.]], dtype=float32)>

In [37]:
tf.reshape(x,(1,2)) @ I

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 77., -88.]], dtype=float32)>

---

### tf.Variable

#### 선언

`-` tf.Variable()로 선언

In [38]:
tf.Variable([1,2,3,4])     #V대문자 주의 #int형 float형 차이

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [39]:
tf.Variable([1.0,2.0,3.0,4.0])

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

`-` tf.constant() 선언후 변환

In [40]:
tf.Variable(tf.constant([1,2,3,4]))   #원하는대로 자유롭게 변환 가능

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

`-` np 등으로 선언후 변환

In [41]:
tf.Variable(np.array([1,2,3,4]))

<tf.Variable 'Variable:0' shape=(4,) dtype=int64, numpy=array([1, 2, 3, 4])>

#### 타입

In [ ]:
type(tf.Variable([1,2,3,4]))

#### 인덱싱

In [42]:
a=tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [43]:
a[:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

#### 연산가능

In [44]:
a=tf.Variable([1,2,3,4])
b=tf.Variable([-1,-2,-3,-4])

In [45]:
a+b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 0], dtype=int32)>

In [46]:
type(a)    #a=-b로 선언하면 형식변함

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [47]:
type(a+b)   #더하면 형식 변하는 것을 볼 수 있음

tensorflow.python.framework.ops.EagerTensor

#### tf.Variable도 쓰기 불편함

In [48]:
tf.Variable([1,2])+tf.Variable([3.14,3.14])   #알아서 형 바꿔주는 거 안됨

InvalidArgumentError: ignored

#### tnp의 은총도 일부만 가능

In [49]:
import tensorflow.experimental.numpy as tnp
tnp.experimental_enable_numpy_behavior()

`-` 알아서 형 변환

In [50]:
tf.Variable([1,2])+tf.Variable([3.14,3.14])

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([4.1400001, 5.1400001])>

`-` .reshape 메소드

In [51]:
tf.Variable([1,2,3,4]).reshape(2,2)
#tf.constant([1,2,3,4]).reshape(2,2)  이거는 되는데 위에는 안됨

AttributeError: ignored

#### 대부분의 동작은 tf.constant랑 큰 차이를 모르겠음

`-` tf.concat

In [52]:
a= tf.Variable([[1,2],[3,4]])
b= tf.Variable([[-1,-2],[-3,-4]])
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]], dtype=int32)>

`-` tf.stack

In [53]:
a= tf.Variable([[1,2],[3,4]])     #stack이라 2차원으로 변하는 것 볼 수 있음
b= tf.Variable([[-1,-2],[-3,-4]])
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[-1, -2],
        [-3, -4]]], dtype=int32)>

#### 변수값변경가능(?)

In [54]:
a = 1
id(a)

133568373915888

In [55]:
a = 456
id(a)

133565694930256

In [56]:
a= tf.Variable([1,2,3,4])
id(a)

133565694988048

In [57]:
a.assign_add([-1,-2,-3,-4])    #주소값 똑같음 - 편집
id(a)

133565694988048

#### 요약

`-` tf.Variable()로 만들어야 하는 뚜렷한 차이는 모르겠음.

`-` 애써 tf.Variable()로 만들어도 간단한연산을 하면 그 결과는 tf.constant()로 만든 오브젝트와 동일해짐.

### 미분

#### 모티브

`-` 예제: 컴퓨터를 이용하여 $x=2$에서 $y=3x^2$의 접선의 기울기를 구해보자.

(손풀이)

$$\frac{dy}{dx}=6x$$

이므로 $x=2$를 대입하면 12이다.

(컴퓨터를 이용한 풀이)

**단계1**

In [58]:
x1=2
y1= 3*x1**2

In [59]:
x2=2+0.000000001
y2= 3*x2**2

In [60]:
(y2-y1)/(x2-x1)

12.0

**단계2**

In [61]:
def f(x):
    return(3*x**2)

In [62]:
f(3)

27

In [63]:
def d(f,x):
    return (f(x+0.000000001)-f(x))/0.000000001

In [64]:
d(f,2)

12.000000992884452

**단계3**

In [65]:
d(lambda x: 3*x**2 ,2)    #함수 계속 선언하는 것 귀찮

12.000000992884452

In [66]:
d(lambda x: x**2 ,0)

1e-09

**단계4**

$$f(x,y)= x^2 +3y$$

In [67]:
def f(x,y):
    return(x**2 +3*y)

In [69]:
d(f,(2,3))    #잘 구해주는 패키지를 이용하자

TypeError: ignored

#### tf.GradientTape() 사용방법

`-` 예제1: $x=2$에서 $y=3x^2$의 도함수값을 구하라.

In [70]:
x=tf.Variable(2.0)        #미분하고 싶은 변수를 variable
a=tf.constant(3.0)

In [71]:
mytape=tf.GradientTape() #기울기 기록?
mytape.__enter__() # 기록 시작
y=a*x**2 # y=ax^2 = 3x^2
mytape.__exit__(None,None,None) # 기록 끝

In [72]:
mytape.gradient(y,x) # y를 x로 미분하라.

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

`-` 예제2: 조금 다른예제

In [73]:
x=tf.Variable(2.0)
#a=tf.constant(3.0)

mytape=tf.GradientTape()
mytape.__enter__() # 기록 시작
a=(x/2)*3 ## a=(3/2)x
y=a*x**2  ## y=ax^2 = (3/2)x^3
mytape.__exit__(None,None,None) # 기록 끝

mytape.gradient(y,x) # y를 x로 미분하라.

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

$$a=\frac{3}{2}x$$
$$y=ax^2=\frac{3}{2}x^3$$

$$\frac{dy}{dx}=\frac{3}{2} 3x^2$$

In [74]:
3/2*3*4

18.0

`-` 테이프의 개념 ($\star$)

(상황)

우리가 어려운 미분계산을 컴퓨터에게 부탁하는 상황임. (예를들면 $y=3x^2$) 컴퓨터에게 부탁을 하기 위해서는 연습장(=테이프)에 $y=3x^2$이라는 수식을 써서 보여줘야하는데 이때 컴퓨터에게 target이 무엇인지 그리고 무엇으로 미분하고 싶은 것인지를 명시해야함.

(1) `mytape = tf.GradientTape()`: tf.GradientTape()는 연습장을 만드는 명령어, 만들어진 연습장을 mytape라고 이름을 붙인다.

(2) `mytape.__enter__()`: 만들어진 공책을 연다 (=기록할수 있는 상태로 만든다)

(3) `a=x/2*3; y=a*x**2`: 컴퓨터에게 전달할 수식을 쓴다

(4) `mytape.__exit__(None,None,None)`: 공책을 닫는다.

(5) `mytape.gradient(y,x)`: $y$를 $x$로 미분하라는 메모를 남기고 컴퓨터에게 전달한다.

`-` 예제3: 연습장을 언제 열고 닫을지 결정하는건 중요하다.

In [75]:
x=tf.Variable(2.0)
a=(x/2)*3 ## a=(3/2)x

mytape=tf.GradientTape()
mytape.__enter__() # 기록 시작
y=a*x**2  ## y=ax^2 = (3/2)x^3
mytape.__exit__(None,None,None) # 기록 끝

mytape.gradient(y,x) # y를 x로 미분하라.

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

`-` 예제4: with문과 함께 쓰는 tf.GradientTape()

In [76]:
x=tf.Variable(2.0)
a=(x/2)*3

In [77]:
with tf.GradientTape() as mytape:
    ## with문 시작
    y=a*x**2
    ## with문 끝

In [78]:
mytape.gradient(y,x) # y를 x로 미분하라.

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

(문법해설)

아래와 같이 쓴다.
```python
with expression as myname:
    ## with문 시작: myname.__enter__()
    blabla ~
    yadiyadi !!
    ## with문 끝: myname.__exit__()
```

(1) expression 의 실행결과 오브젝트가 생성, 생성된 오브젝트는 myname라고 이름붙임. 이 오브젝트는 `.__enter__()`와 `.__exit__()`를 숨겨진 기능으로 포함해야 한다.

(2) with문이 시작되면서 `myname.__enter__()`이 실행된다.

(3) 블라블라와 야디야디가 실행된다.

(4) with문이 종료되면서 `myname.__exit__()`이 실행된다.

`-` 예제5: 예제2를 with문과 함께 구현

In [79]:
x=tf.Variable(2.0)

with tf.GradientTape() as mytape:
    a=(x/2)*3 ## a=(3/2)x
    y=a*x**2  ## y=ax^2 = (3/2)x^3

mytape.gradient(y,x) # y를 x로 미분하라.

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

`-` 예제6: persistent = True

(관찰1)

In [80]:
x=tf.Variable(2.0)

with tf.GradientTape() as mytape:
    a=(x/2)*3 ## a=(3/2)x
    y=a*x**2  ## y=ax^2 = (3/2)x^3


In [81]:
mytape.gradient(y,x) # 2번이상 실행해서 에러를 관측하라 #persistent=True로 주면 2번 이상 실행해도 그대로 실행됨

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

(관찰2)

In [82]:
x=tf.Variable(2.0)

with tf.GradientTape(persistent=True) as mytape:
    a=(x/2)*3 ## a=(3/2)x
    y=a*x**2  ## y=ax^2 = (3/2)x^3


In [83]:
mytape.gradient(y,x) # 2번이상실행해도 에러가 나지않음

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

`-` 예제7: watch

(관찰1)

In [84]:
x=tf.constant(2.0)   #constant로 실행했을 때

with tf.GradientTape(persistent=True) as mytape:
    a=(x/2)*3 ## a=(3/2)x
    y=a*x**2  ## y=ax^2 = (3/2)x^3


In [85]:
print(mytape.gradient(y,x))

None


(관찰2)

In [86]:
x=tf.constant(2.0)
with tf.GradientTape(persistent=True) as mytape:
    mytape.watch(x) # watch이용해서 수동감시 = variable과 같은 형태로
    a=(x/2)*3 ## a=(3/2)x
    y=a*x**2  ## y=ax^2 = (3/2)x^3

In [87]:
print(mytape.gradient(y,x))

tf.Tensor(18.0, shape=(), dtype=float32)


In [88]:
tf.GradientTape?

(관찰3)

In [93]:
x=tf.Variable(2.0)
with tf.GradientTape(persistent=True,watch_accessed_variables=False) as mytape: # 자동감시 모드 해제
    a=(x/2)*3 ## a=(3/2)x
    y=a*x**2  ## y=ax^2 = (3/2)x^3

In [94]:
print(mytape.gradient(y,x))

None


(관찰4)

In [95]:
x=tf.Variable(2.0)   #한다
with tf.GradientTape(persistent=True,watch_accessed_variables=False) as mytape: # 자동감시 모드 해제 #안한다
    mytape.watch(x) #한다
    a=(x/2)*3 ## a=(3/2)x
    y=a*x**2  ## y=ax^2 = (3/2)x^3

In [96]:
print(mytape.gradient(y,x))

tf.Tensor(18.0, shape=(), dtype=float32)


(관찰5)

In [97]:
x=tf.Variable(2.0)
with tf.GradientTape(persistent=True) as mytape:
    mytape.watch(x)
    a=(x/2)*3 ## a=(3/2)x
    y=a*x**2  ## y=ax^2 = (3/2)x^3

In [98]:
print(mytape.gradient(y,x))

tf.Tensor(18.0, shape=(), dtype=float32)


`-` 예제9: 카페예제로 돌아오자.

`-` 예제10: 카페예제의 매트릭스 버전

`-` 예제11: 위의 예제에서 이론적인 $\boldsymbol{\beta}$의 최적값을 찾아보고 (즉 $\hat{\boldsymbol{\beta}}$을 찾고) 그곳에서 loss의 미분을 구하라. 구한결과가 $\begin{bmatrix}0 \\ 0 \end{bmatrix}$ 임을 확인하라.